Toolbar Done button visibility.
esafirm/android-image-picker pull request #347
Opened 2021-04-02 07:17 UTC by dilip786

Added a new variable in ImagePickerConfig.kt Whether to show Done button or not always, We already had a chat on this and here is the bug link [(https://github.com/esafirm/android-image-picker/issues/339 )].

This is blocker to my release, Please have a look and let me know if you need any changes.

2021-04-03 00:21 UTC, esafirm requested changes

2021-04-03 00:21 UTC, esafirm commented on imagepicker/src/main/java/com/esafirm/imagepicker/helper/ConfigUtils.kt
> +    fun getDoneButtonTextVisibility(config: ImagePickerConfig): Boolean {
You don't need helper function if it just accessing a property

2021-04-03 00:21 UTC, esafirm commented on imagepicker/src/main/java/com/esafirm/imagepicker/features/common/BaseConfig.kt
> +    abstract var showDoneButtonAlways: Boolean
I think you should only add this in `ImagePickerConfig` since it's not affecting `CameraOnly` functionality?

2021-04-05 07:09 UTC, dilip786 reviewed
Updated code as per your request.

2021-04-06 12:40 UTC, dilip786 commented
@esafirm Can you please have a look at my pr as this is blocker to my release. thanks in advance.

2021-04-08 02:16 UTC, esafirm commented
LGTM 👍 Thanks for the PR @dilip786

2021-04-08 02:16 UTC, merged

2021-04-08 02:20 UTC, esafirm commented
Packagin this as `3.0.0-alpha2` @dilip786

2021-04-08 02:24 UTC, dilip786 commented
Thanks Esafirm/Android-Image-Picker

On Thu, 8 Apr, 2021, 7:51 am Esa Firman, ***@***.***> wrote:

> Packagin this as 3.0.0-alpha2 @dilip786 <https://github.com/dilip786>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esafirm/android-image-picker/pull/347#issuecomment-815397284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRKBYCK3WHEUT4PSCZR7V3THUHJPANCNFSM42INRCYA>
> .
>

2021-04-08 07:26 UTC, dilip786 commented
Hey, Unable to import this package 3.0.0-alpha2, Getting errors. Can you help on this pls

2021-05-16 17:24 UTC, esafirm commented
The artifact is now `com.github.esafirm:android-image-picker:x.y.z` 
Sorry for the late response

2021-07-29 12:55 UTC, yravid commented
Can it be released also as part of the v2 release train?  Thank you @esafirm 🥇